# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane 

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']

    match(app_identifier: "com.berkspar.hubfinder", type: "appstore", readonly: true)
    gym(scheme: "Runner", workspace: "Runner.xcworkspace", export_method: "app-store", configuration: "Release", clean: true, output_directory: "build")
    testflight(ipa: "build/Runner.ipa", skip_waiting_for_build_processing: true)
    clean_build_artifacts
  end
end
